#!/usr/bin/sh

group=$1


if [ ! -z $group ];then

	mkdir /data/BCI-Haemato/Yi/change_bed/05.extracted/$group 
	# step_1 63k_200k interaction list 
	awk 'NR==FNR{a[$1]=$1}NR>FNR{if(a[$1]!=""){print a[$1]}else{next}}' /data/BCI-Haemato/Yi/change_bed/04.merge/$group/lst/merge_63k.lst /data/BCI-Haemato/Yi/change_bed/04.merge/$group/lst/merge_200k.lst > /data/BCI-Haemato/Yi/change_bed/05.extracted/$group/63k_200k.lst

	# step_2 63k_300k interaction list
	awk 'NR==FNR{a[$1]=$1}NR>FNR{if(a[$1]!=""){print a[$1]}else{next}}' /data/BCI-Haemato/Yi/change_bed/04.merge/$group/lst/merge_63k.lst /data/BCI-Haemato/Yi/change_bed/04.merge/$group/lst/merge_300k.lst > /data/BCI-Haemato/Yi/change_bed/05.extracted/$group/63k_300k.lst

	# step_3 200k_300k intreaction list
	awk 'NR==FNR{a[$1]=$1}NR>FNR{if(a[$1]!=""){print a[$1]}else{next}}' /data/BCI-Haemato/Yi/change_bed/04.merge/$group/lst/merge_200k.lst /data/BCI-Haemato/Yi/change_bed/04.merge/$group/lst/merge_300k.lst > /data/BCI-Haemato/Yi/change_bed/05.extracted/$group/200k_300k.lst

	# step_4 merge list
	cat /data/BCI-Haemato/Yi/change_bed/04.merge/$group/extracted/*lst |sort -u|awk 'FNR==NR{a[$1]=$1}NR>FNR{if(a[$4]!=""){print $0}}' - /data/BCI-Haemato/Yi/change_bed/04.merge/$group/merge/merge.bed > /data/BCI-Haemato/Yi/change_bed/05.extracted/$group/extracted_$group".bed" 
else
	echo "group not dentified"
fi
